pipeline {
    agent any
    stages {
        stage('Hello') {
               when {
                    anyOf { 
                        branch 'main*'
                        branch 'dev*'
                        branch 'rel/*'
                    }
               }
            steps {
                echo "lendo branch  ${env.BRANCH_NAME}"
            }
        }
    }
}
