pipeline {
    agent any
    stages {
        stage('Hello') {
               when {
                    anyOf { 
                        branch 'main*'
                        branch 'dev*'
                    }
               }
            steps {
		    script{
	    	    	def jobName = new Date()
				jobName = jobName.format("yyMMdd.HHmm", TimeZone.getTimeZone('UTC'))
		        	currentBuild.displayName = "$jobName"
		        	jobName = "teste-nome"+"_"+jobName
				node {
					echo "job name $jobName"
				}
		    }
	    }
    
	}

    }
}
