pipeline {
    agent any

    stages {
        stage('Example') {
            steps {
                sh '''
                echo ˜$(env.BRANCH_NAME)˜
                echo ˜Teste leitura da variavel˜
                '''
            }
        }
    }
}
